export * from '@/components/page/personal/Personal'
export * from '@/components/page/text/Text'
export * from '@/components/page/projects/Projects'
export * from '@/components/page/credentials/Credentials'
export * from '@/components/page/blog/Blog'
export * from '@/components/page/profiles/Profiles'
